# This is a basic workflow to help you get started with Actions

name: AppImage Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - '**.bash'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Prepare for build
      run: |
        [[ -f "src/script/procspin.bash" ]] || exit 1
        if [[ ! -d "src/appimage/procspin.AppDir/usr/bin" ]]; then
          mkdir -p "src/appimage/procspin.AppDir/usr/bin" || exit 2
        fi
        cp "src/script/procspin.bash" "src/appimage/procspin.AppDir/usr/bin/procspin" || exit 3
        cp "src/script/procspin.bash" "dist/script/procspin.bash" || exit 4
    # Runs a set of commands using the runners shell
    - name: Download building tools & executing AppImage build
      if: success()
      run: |
        if [[ -f "src/appimage/procspin.AppDir/usr/bin/procspin" ]]; then
          wget -nv -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          ./build.sh
        else exit 5; fi
    - name: Create Release
      if: success()
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: Continuous
        name: Continuous Build
        prerelease: False
        artifacts: "dist/appimage/procspin-x86_64.AppImage,dist/script/procspin.bash"
        token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built Linux Binary
