name: MD5 Checks
on:
  repository_dispatch:
    types: [md5-check]
jobs:
  md5_checks:
    name: Check MD5 of Project Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check and Create Directories and Files
        run: |
          nl='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAMAAAAolt3jAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAB11BMVEUAAAA9U2GDnayLpraOqLeQqbiRqriPqLaPqLaRqriDnaw9U2Fid4SKp7iKp7hid4RfdYGHpbdYbnuCorRSaHV9nrFMYm93ma1HXGlwlKlwlKlBV2NojqQ7UV1hiKA2S1hYgpswRlJQfJcwRlIkMjlDbIVMfJpNfptOfptNfZpRfplTf5lMfJlOfptNfptDbIUkMjkHAAAuR1YzUWMzUWMzUmM0UmQzUWMyUWM0UmQzUmMzUWMzUWMuR1YHAACNsMWRs8aXt8mbuMm3ydSbuMmRs8aIrsONscWStMeZtsfk6u3k6u2ZtseStMeIrsOGrMKKr8SMr8Oswc3u8PHu8PGswc6Mr8OCqcCFrMKJrsOTssTT3OLS3OKTssSJrsOCqcB9pr5/p7+CqcCApryYs8Sdt8aApryCqb9/p799pr52obp4o7x9o7qswc7F09vO2eCwxNCCp7x4ort2obpvnLdxnbd9orjK1t3T3OLK1t7Y4OSFp7twnLZvnbdomLRolrKTsMHb4eWju8mRrsDd4+aiushplrJomLRhkrBik7Bmkq25ydLY3uLW3eHI09ptl69hkrBhkrBZjq1bj65ej613nbSRrr+etsV3nbRika1bjq5Zjq3///97NWaUAAAAP3RSTlMAAlOMioqKioqKUwIMwcEMDsQOxA7EDsQOxMQOxA7EDsQOxA4Lq/Lv7+/v7+/v76sLASI+Pj4+Pj4+Pj4+IgH2SccMAAAAAWJLR0SccbzCJwAAAAd0SU1FB+QIGBYnM5liyzQAAADPSURBVAjXY2BABYxMzCysbOwcnKwszFzcDDy89g6OTs7OLo6u9nz8DAKCbu4enl7ePr7ufoICDELC/gGBQcEhoWEB/sJCDCKi4RGRUdExsXER8aIiDGLiCYlJySmpaekZmeJiDBKSWdk5uXn5BYVFxVISDNIyJaVl5RWVVdU1tTLSDLJydfUNjU3NLa1t7XKyDPIKHZ1d3T29ff0TJirIMygqTZo8Zeq06TNmzpqtpMygoqqmrqGppa2jq6emb8BgaGRsYmpmbmFpZW1jawcAIDgy9UQeYeoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjAtMDgtMjRUMjI6Mzk6NTEtMDQ6MDBWWeqAAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIwLTA4LTI0VDIyOjM5OjUxLTA0OjAwJwRSPAAAAABJRU5ErkJggg=='
          [[ -f "dist/script/procspin.bash" ]] || exit 1
          [[ -f "dist/appimage/procspin-x86_64.AppImage" ]] || exit 2
          if ! [[ -d "docs/json" ]]; then
            mkdir -p docs/json || exit 3
          fi
          if ! [[ -f "docs/json/script-md5.json" ]]; then
            touch docs/json/script-md5.json || exit 4
          fi
          if ! [[ -f "docs/json/script-md5.json" ]]; then
            touch docs/json/appimage-md5.json || exit 5
          fi
          json_template='{\n\t"schemaVersion": 1,\n\t"color": "00aedb",\n\t"label": "PLACEHOLDERL",\n\t"message": "PLACEHOLDERM",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "PLACEHOLDERN"\n}'
          echo -e "$json_template" > docs/json/script-md5.json || exit 6
          echo -e "$json_template" > docs/json/appimage-md5.json || exit 7
          sed -i "s/\"label\": \".*\"/\"label\": \"Script MD5\"/g" docs/json/script-md5.json
          sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum dist/script/procspin.bash | cut -d' ' -f 1)\"/g" docs/json/script-md5.json
          sed -i "s/\"namedLogo\": \".*\"/\"namedLogo\": \"bash\"/g" docs/json/script-md5.json
          sed -i "s/\"label\": \".*\"/\"label\": \"AppImage MD5\"/g" docs/json/appimage-md5.json
          sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum dist/appimage/procspin-x86_64.AppImage | cut -d' ' -f 1)\"/g" docs/json/appimage-md5.json
          sed -i "s/\"namedLogo\": \".*\"/\"namedLogo\": \"$nl\"/g" docs/json/appimage-md5.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Created MD5 Json Endpoints